name: Initiate Release
 
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        type: [ubuntu16.04, ubuntu18.04]
    runs-on: ubuntu-latest
    steps:
      - name: Perform Release 
        run: |
          echo ${{ matrix.type }}