name: Initiate Release
 
on:
  push
    # tags:
    #   - "v*"

jobs:
  release:
    strategy:
      matrix:
        sku: [
        'ubuntu16;deb;oss',
        'ubuntu16;deb;commercial',
        'ubuntu18;deb;oss',
        'ubuntu18;deb;commercial',
        'windows10;zip;oss',
        'windows10;chocolatey;oss',
        'windows10;zip;commercial',
        'amazon-linux2;rpm;commercial',
        'oracle-linux2;rpm;commercial',
        'centos7;rpm;commercial',
        ]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Perform Release 
        shell: pwsh
        run: |
          $os,$type,$sku = "${{ matrix.sku }}".Split(';');
          Write-Host "Operating System: $($os)"
          Write-Host "Type : $($type)"
          Write-Host "Sku : $($sku)"
