name: Initiate Release
 
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        type: [ubuntu16: {
          packages: [oss, commercial]
        }, ubuntu18: {
          packages: [oss, commercial]
        }]
    runs-on: ubuntu-latest
    steps:
      - name: Perform Release 
        run: |
          echo "operating system: ${{ matrix.type.packages[0] }}"